name: Task Sync

on:
  push:
    paths:
      - 'tasks/task.md'  # タスクファイルが変更された場合にトリガー

jobs:
  sync-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Sync Tasks with GitHub Issues
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DOCUMENT_REPOS: ${{ secrets.DOCUMENT_REPOS }}
        run: |
          python sync_tasks.py

